---
title: 데이터 시각화 모범 사례
subtitle: 데이터 산출물을 더 읽기 쉽고, 접근하기 쉽고, 영향력 있게 만들기 위한 통찰력, 조언 및 예제(코드 포함)
author: "Andreas Krause, Nicola Rennie, & Brian Tarran"
bibliography: references.bib
nocite: |
  @*
format:
  pdf:
    toc: true
    toc-depth: 2
    number-sections: true
    number-depth: 2
    output-file: "RSS-data-vis-guide"
    output-ext:  "pdf"
    mainfont: "Noto Serif CJK KR"
    sansfont: "Noto Sans CJK KR"
    linkcolor: RSSblue
    urlcolor: RSSblue
    include-in-header: 
       - "styles.tex"
editor: source
---

```{r}
#| echo: false
#| eval: true
process_qmd <- function(file, fpath_in = "images/", fpath_out = "images/") {
  doc <- readLines(file)
  end_yaml <- which(doc == "---")[2]
  out_doc <- doc[seq(end_yaml+1, length(doc))]
  if (fpath_in != fpath_out) {
    out_doc <- stringr::str_replace_all(out_doc, fpath_in, fpath_out)
  }
  res <- knitr::knit_child(text = out_doc, quiet = TRUE, options = list(eval = FALSE, echo = TRUE))
  return(res)
}
```

# 소개

```{r}
#| output: asis
#| echo: false
#| eval: true
#| message: false
idx <- process_qmd("index.qmd")
cat(unlist(idx), sep = '\n')
```

# 이 가이드 사용법

```{r}
#| output: asis
#| echo: false
#| eval: true
#| message: false
howto <- process_qmd("howto.qmd")
cat(unlist(howto), sep = '\n')
```

# 데이터 시각화를 하는 이유

```{r}
#| output: asis
#| echo: false
#| eval: true
#| message: false
why <- process_qmd("docs/why-visualise.qmd", fpath_in = "images/", fpath_out = "docs/images/")
cat(unlist(why), sep = '\n')
```

# 시각화의 원칙과 요소

```{r}
#| output: asis
#| echo: false
#| eval: true
#| message: false
principles <- process_qmd("docs/principles.qmd", fpath_in = "images/", fpath_out = "docs/images/")
cat(unlist(principles), sep = '\n')
```

# 시각화 유형 선택하기

```{r}
#| output: asis
#| echo: false
#| eval: true
#| message: false
choosing <- process_qmd("docs/choosing.qmd", fpath_in = "images/", fpath_out = "docs/images/")
cat(unlist(choosing), sep = '\n')
```

# 접근성을 위한 차트 스타일링

```{r}
#| output: asis
#| echo: false
#| eval: true
#| message: false
styling <- process_qmd("docs/styling.qmd", fpath_in = "images/", fpath_out = "docs/images/")
cat(unlist(styling), sep = '\n')
```


# RSS 간행물을 위한 차트 스타일링

```{r}
#| output: asis
#| echo: false
#| eval: true
#| message: false
tools <- process_qmd("docs/tools.qmd", fpath_in = "images/", fpath_out = "docs/images/")
cat(unlist(tools), sep = '\n')
```

# 참고 문헌

```{r}
#| output: asis
#| echo: false
#| eval: true
#| message: false
refs <- process_qmd("docs/references.qmd")
cat(unlist(refs), sep = '\n')
```

# 저자 소개

```{r}
#| output: asis
#| echo: false
#| eval: true
#| message: false
about <- process_qmd("about.qmd")
cat(unlist(about), sep = '\n')
```

# 이용 약관

```{r}
#| output: asis
#| echo: false
#| eval: true
#| message: false
ts_and_cs <- process_qmd("ts-and-cs.qmd")
cat(unlist(ts_and_cs), sep = '\n')
```
