---
title: "이 가이드 사용법"
toc: true
repo-actions: false
---

우리는 이 가이드가 처음부터 끝까지 읽히도록 설계하여, 각 섹션이 이전 섹션의 토대 위에 구축되도록 했습니다. 가이드를 처음 읽는다면 이 방식대로 읽을 것을 권장합니다. 하지만 데이터 시각화의 특정 측면에 대한 지침을 찾는 사람들은 이 웹사이트의 검색 및 탐색 기능을 활용할 수 있습니다.

오프라인으로 읽는 것을 선호한다면 [가이드를 PDF로 다운로드](RSS-data-vis-guide.pdf)할 수 있습니다. 오른쪽 탐색 메뉴에 표시되는 "Other Formats > PDF" 옵션을 사용하여 가이드의 개별 섹션을 별도의 PDF로 다운로드할 수도 있습니다.

본문 전체에 걸쳐 차트와 그래프의 예시를 볼 수 있습니다. 이러한 예시 중 상당수에 대해 시각화를 재현할 수 있도록 R 코드를 제공하며, 여러분이 직접 해보고 자신의 목적에 맞게 코드를 수정해 볼 것을 권장합니다.

## 이 가이드에 기여하는 방법

#### 제안하거나 질문하기

GitHub 리포지토리의 [생각 공유(Discussions)](https://github.com/royal-statistical-society/datavisguide/discussions) 섹션에서 토론을 시작해 주세요.

#### 버그나 오류를 발견했다면

다음 중 하나를 수행해 주세요:

1.  GitHub 리포지토리의 [문제(Issues)](https://github.com/royal-statistical-society/datavisguide/issues) 섹션에 이슈를 제기합니다. 웹사이트의 'Report an issue' 링크 중 하나를 사용하여 이 작업을 수행할 수 있습니다. 또는
2.  리포지토리를 포크(Fork)하고, 관련 파일을 수정한 후, 우리 리포지토리의 `main` 브랜치에 풀 리퀘스트(Pull Request)를 보냅니다. 웹사이트의 'Edit this page' 링크 중 하나를 사용하여 이 작업을 수행할 수 있습니다.

#### 가이드에 새로운 기능이나 섹션을 추가하고 싶다면

1.  GitHub 리포지토리의 [문제(Issues)](https://github.com/royal-statistical-society/datavisguide/issues) 섹션에 이슈를 제기하고, 'enhancement' 태그를 단 후 제안하는 기여 내용을 설명합니다.
2.  리포지토리를 포크하고, 예를 들어 `my-new-feature-or-section`과 같은 이름으로 새 브랜치를 만듭니다.
3.  브랜치에 콘텐츠, 코드 및 파일을 추가합니다.
4.  우리 리포지토리의 `main` 브랜치에 풀 리퀘스트를 보냅니다.

기여 절차에 대한 자세한 내용은 리포지토리의 [README 파일](https://github.com/royal-statistical-society/datavisguide/tree/main#readme)에서 확인할 수 있습니다.

## 이 가이드의 다른 사용자들과 교류하는 방법

독자 여러분은 GitHub 리포지토리의 [생각 공유(Discussions)](https://github.com/royal-statistical-society/datavisguide/discussions) 섹션을 최대한 활용하시기 바랍니다. 웹사이트와 리포지토리의 사용 및 모든 기여는 [행동 강령](ts-and-cs.qmd#contributor-covenant-code-of-conduct)의 적용을 받습니다.

## 저작권, 재사용, 배포 및 면책 조항

이 가이드의 저작권은 © 2024 Andreas Krause, Nicola Rennie 및 영국 왕립 통계 학회(Royal Statistical Society)에 있습니다. 편집팀이 작성하고 이 가이드에 게시된 콘텐츠는 [Creative Commons Attribution 4.0 (CC BY 4.0) International 라이선스](http://creativecommons.org/licenses/by/4.0/?ref=chooser-v1) 하에 배포됩니다. 이는 원저작자를 표시하는 한, 어떤 목적으로든 사용 및 수정이 가능함을 의미합니다. 이 가이드에 기여함으로써 기여자들은 자신의 작업물을 동일한 조건으로 라이선스하는 것에 동의하게 됩니다.

> **인용 방법:** Krause, Andreas, Nicola Rennie, and Brian Tarran. "Best Practices for Data Visualisation." Royal Statistical Society, 1 February 2024. https://doi.org/10.5281/zenodo.10600718.

이 웹사이트에 게시된 사실 및 의견 진술은 각각의 저자 및 기여자의 것이며 영국 왕립 통계 학회(RSS)의 입장과는 다를 수 있습니다.

저자들은 이 웹사이트의 콘텐츠를 책임감 있고 신중하게 준비했습니다. 그러나 저자와 RSS는 이 웹사이트나 다른 링크된 웹사이트 또는 그 이후의 링크에 포함된 정보의 정확성에 대해 명시적이든 묵시적이든 어떠한 보증도 부인합니다. 전체 [이용 약관](ts-and-cs.qmd)을 참조하십시오.
