---
title: "데이터 시각화 모범 사례"
subtitle: "데이터 산출물을 더 읽기 쉽고, 접근하기 쉽고, 영향력 있게 만들기 위한 통찰력, 조언 및 예제(코드 포함)"
repo-actions: false  
---

통계학은 "데이터를 수집, 분석, 제시 및 해석하는 과학"입니다[@statistics]. 데이터 제시는 해석과 그에 따른 의사결정을 지원하고 안내하는 중요한 수단입니다. 효과적인 표시를 위한 기법들이 존재합니다. 이것이 바로 이 가이드가 다루는 내용입니다.

좋은 데이터 시각화는 데이터 제시의 기술적 측면에 대한 이해와 신중한 고려를 필요로 합니다. 하지만 여기에는 창의적인 요소도 포함됩니다. 저자는 전달하고자 하는 "이야기"에 대해 선택을 하고, 청중에게 그 이야기를 가장 효과적으로 전달할 필요성에 따라 디자인을 결정합니다. 소프트웨어 시스템은 대부분의 그래픽 요소에 대해 기본 설정을 사용합니다. 그러나 각 시각화에는 고유한 이야기가 있으므로, 작성 중인 시각화에 대한 설정을 적극적으로 고려하고 선택해야 합니다.

이 가이드는 데이터 시각화의 예술과 과학이라는 두 가지 측면을 모두 다룹니다. 주로 [영국 왕립 통계 학회 간행물](https://rss.org.uk/news-publication/publications/) -- 주로 [*Significance* 매거진](https://academic.oup.com/jrssig), [*Journal of the Royal Statistical Society Series A*](https://academic.oup.com/jrsssa), [Real World Data Science](https://realworlddatascience.net/) -- 기여자를 위해 작성되었지만, 여기에 담긴 정보와 조언이 어떤 데이터 시각화 작업에도 광범위하게 관련되고 유용할 것이라 믿습니다.

이 가이드의 가장 중요한 목표는 독자들에게 고품질이고, 가독성이 좋으며, 정보를 효과적으로 전달하고, 표시 및 해석이 정확하며, 의도한 목적을 달성하는 데이터 시각화를 만드는 데 필요한 기초를 갖추게 하는 것입니다. 이 가이드는 [우리가 데이터를 시각화하는 이유](docs/why-visualise.qmd)에 대한 개요로 시작하여, 차트와 표의 구조, 그리고 가독성을 높이기 위해 이러한 구조를 개선하는 방법을 포함한 [데이터 시각화의 핵심 원칙과 요소](docs/principles.qmd)를 논의합니다. [차트 스타일링](docs/styling.qmd)을 개선하는 데 도움이 되는 구체적인 조언, 예제 및 코드가 제시되며, 특히 접근성에 중점을 둡니다. [RSS 간행물을 위한 차트 스타일링](docs/tools.qmd)에 대한 전용 섹션이 있으며, 독자들은 당면한 데이터에 [적합한 차트 유형을 선택](docs/choosing.qmd)하기 위한 리소스 링크도 찾을 수 있습니다.

이 가이드를 구성하면서 [저자](about.qmd)는 해당 분야의 전문가들이 만든 많은 훌륭한 교과서, 논문 및 기타 자료를 참고했습니다. 참고문헌은 전체에 걸쳐 찾아볼 수 있으며 [전용 페이지](docs/references.qmd)에도 수집되어 있습니다. 독자들은 데이터 시각화의 예술과 과학에 대한 이해와 감상을 깊게 하기 위해 원본 소스를 찾아볼 것을 권장합니다.
