---
title: 참고 문헌 및 리소스
nocite: |
  @*
---

## 가이드에서 참조된 텍스트

::: {#refs}
:::

## 추가 읽기 자료

#### Functional Aesthetics for Data Visualization.

@Setlur2022

추천 이유: *이 책은 연구와 실무를 연결하며, 인지 심리학, 데이터 리터러시, 시각 디자인의 아이디어를 결합합니다. 이 책의 아이디어는 단순한 차트를 넘어 대화형 대시보드 및 시각화를 포함한 복잡한 시각적 디스플레이까지 확장될 수 있습니다.*

#### Better Data Visualizations: A Guide for Scholars, Researchers, and Wonks.

@Schwabish2021

추천 이유: *이 책은 보여주고자 하는 내용에 따라 어떤 유형의 데이터 시각화가 가장 적절한지 안내합니다. 뿐만 아니라 시각적 인지 이론을 사용하여 왜 어떤 차트가 다른 차트보다 읽기 쉬운지 설명합니다.*

#### Data Feminism.

@DIgnazio2020

추천 이유: *우리는 데이터 시각화애 대해 이야기할 때 종종 "스토리텔링"이라는 용어를 듣게 되는데, 여기서 스토리텔러의 역할을 기억해야 합니다. 이 책에서 저자들은 우리가 데이터로 작업할 때 데이터가 수집된 이유와 그것이 무엇을 위해 사용될 수 있는지에 대해서도 생각해야 한다는 점을 포함하여 몇 가지 중요한 점을 지적합니다.*

#### Preference for and understanding of graphs presenting health risk information. The role of age, health literacy, numeracy and graph literacy.

@VanWeert2021

추천 이유: *환자들은 종종 차트와 표 형식의 건강 위험 정보에 대한 데이터를 받습니다. 이 기사는 환자들이 다양한 차트 유형을 통해 자신에게 제시된 정보를 얼마나 잘 이해하는지 조사합니다. 환자들이 선호하는 차트 유형이 항상 가장 잘 이해하는 차트 유형은 아니라는 것을 발견했습니다.*

## 추가 리소스

### 교육 과정

#### [데이터 제시 (RSS)](https://rss.org.uk/training-events/training/public-courses/introduction-to-statistics/presenting-data/presenting-data-2021-12-25,-9-00am/#eventoverview)

이 온라인 과정은 통계 정보 제시의 기초입니다. 표, 차트, 지도 및 텍스트로 정보를 제시하는 기본 원칙을 설명합니다. 이러한 원칙들은 예시를 통해 설명된 다음 실습을 통해 강화됩니다.

#### [Tableau에서의 데이터 탐색 (RSS)](https://rss.org.uk/training-events/training/public-courses/software-training/data-exploration-in-tableau/)

Tableau는 단순한 데이터 시각화 도구 그 이상입니다. 또한 여러 데이터 소스를 조작하고, 사용자 정의 차트를 만들고, 예측 모델을 구축하고, 플롯을 대화형 대시보드 및 프레젠테이션으로 전환할 수 있는 기능을 제공합니다.

이 가상 과정은 두 번의 오후에 걸쳐 진행됩니다. 데이터를 랭글링(wrangling)하고, 데이터 분석을 수행하고, 결과를 시각적으로 전달하는 과정을 안내합니다. 이 과정을 마치면 자신의 데이터를 조작하여 사용자 정의 차트를 구축할 수 있게 됩니다. Tableau에서 지리적 데이터로 작업하는 방법, 예측 모델을 사용하여 예측하는 방법, 대화형 대시보드 및 스토리를 만들어 작업을 공유하는 방법을 배우게 됩니다.

#### [데이터 탐색 및 기본 통계를 위한 Power BI (RSS)](https://rss.org.uk/training-events/training/public-courses/software-training/power-bi-for-data-exploration-and-basic-statistics/)

Power BI는 대화형 보고서 및 대시보드 제작을 위한 표준 도구로 빠르게 자리 잡고 있으며, 이 과정은 데이터 준비부터 시각적 개체 구축 및 공유에 이르기까지 워크플로에 중점을 두고 Power BI에 대한 체계적인 소개를 제공합니다. 의도한 청중을 기반으로 적절한 수준의 기능과 사용성을 달성하는 데 도움이 되도록 디자인 이슈에 중점을 둡니다. 또한 기본 통계 사용에도 특별한 주의를 기울일 것입니다.

#### [ggplot2를 사용하여 R에서 출판 품질 차트 게시하기 (RSS)](https://rss.org.uk/training-events/training/public-courses/software-training/publishing-quality-charts-in-r-with-ggplot2/)

이 강사가 주도하는 가상 과정에서는 tidyverse와 ggplot2를 사용하여 R에서 출판 품질의 차트를 재현 가능하게 만드는 방법을 소개합니다.

### 로우 코드/노 코드 시각화 도구

#### Datawrapper

<https://www.datawrapper.de/>

#### Flourish

<https://flourish.studio/>
